x-common-variables: &common-variables
  MYCALL: CHANGEME

services:

  # ka9q-radio SDR service
  ka9q-radio:
    #build: https://github.com/snh/dockerfiles.git#main:ka9q-radio
    build: ./ka9q-radio
    command: bash -c "
        sdrplay_apiService &
        radiod /etc/radio/radiod.conf
      "
    restart: 'always'
    cap_add:
      - CAP_NET_ADMIN
      - CAP_SYS_NICE
    container_name: ka9q-radio
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    network_mode: host
    tty: true
    volumes:
      - ./ka9q-radio/radiod.conf:/etc/radio/radiod.conf:ro
      - ./ka9q-radio/wisdomf:/etc/fftw/wisdomf
      - ./ka9q-radio/wisdom:/var/lib/ka9q-radio/wisdom
      - /var/run/dbus:/var/run/dbus

  chasemapper:
    image: ghcr.io/projecthorus/chasemapper:latest
    restart: 'always'
    devices:
      - "/dev/ttyACM0:/dev/ttyUSB0"
    volumes:
      - type: 'bind'
        source: './chasemapper/horusmapper.cfg'
        target: '/opt/chasemapper/horusmapper.cfg'
      - type: 'bind'
        source: './chasemapper/log_files/'
        target: '/opt/chasemapper/log_files/'
      - type: 'bind'
        source: './chasemapper/gfs/'
        target: '/opt/chasemapper/gfs/'
      - type: 'bind'
        source: './maps/'
        target: '/opt/chasemapper/Maps/'
    network_mode: 'host'

  maptilesdownloader:
    image: ghcr.io/ke5gdb/maptilesdownloader:testing
    restart: 'always'
    network_mode: host
    tty: true
    volumes:
      - ./maps/:/opt/MapTilesDownloader/output/

  wenet-431500:
    #image: ghcr.io/projecthorus/wenet:latest
    image: ghcr.io/ke5gdb/wenet:testing
    restart: 'always'
    environment:
      <<: *common-variables
      RXFREQ: 431500000
      DEVICE: 'wenet-1-pcm.local'
      BAUD_RATE: 115200
      OVERSAMPLING: 8
      UDP_PORT: 55673
      IMAGE_PORT: 7890
      WEB_PORT: 5003
      SDR_TYPE: KA9Q
      UPLOAD_ENABLE: 1
    volumes:
      - type: 'bind'
        source: './wenet/rx_images/'
        target: '/opt/wenet/rx_images/'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432550:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432550000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'
    
  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432600:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432600000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432625:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432625000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

      # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432650:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432650000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432675:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432675000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432700:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432700000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432725:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432725000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432750:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432750000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432775:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432775000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432800:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432800000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432850:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432850000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432900:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432900000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'

  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-432950:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 432950000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'
    
  # Receiver instance name (e.g. "horus-434200" or "wenet-443500")
  horus-433000:
    image: ghcr.io/projecthorus/horusdemodlib
    # image: horusdemodlib
    restart: 'always'
    environment:
      # Change this to match the PCM device defined in 
      SDR_DEVICE: rtl-sdr-pcm.local
      STATS_OUTPUT: 0
      DECODER: horus_demod
      DEMODSCRIPT: "docker_ka9q_single.sh"
      # Receive *centre* frequency, in Hz
      RXFREQ: 433000000
      # Frequency estimator bandwidth. The wider the bandwidth, the more drift and frequency error the modem can tolerate,
      # but the higher the chance that the modem will lock on to a strong spurious signal.
      RXBANDWIDTH: 10000
    command: 'bash -c $${DEMODSCRIPT}'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'bind'
        source: './horusdemodlib/user.cfg'
        target: '/user.cfg'
      - type: 'bind'
        source: '/var/run/avahi-daemon/socket'
        target: '/var/run/avahi-daemon/socket'
    network_mode: 'host'
